// app/checkout/countries.ts
export const countriesList = [
  { name: "United States", flag: "🇺🇸", code: "+1", isoCode: "US" },
  { name: "Afghanistan", flag: "🇦🇫", code: "+93", isoCode: "AF" },
  { name: "Aland Islands", flag: "🇦🇽", code: "+358", isoCode: "AX" },
  { name: "Albania", flag: "🇦🇱", code: "+355", isoCode: "AL" },
  { name: "Alderney", flag: "🇬🇬", code: "+44", isoCode: "GG" },
  { name: "Algeria", flag: "🇩🇿", code: "+213", isoCode: "DZ" },
  { name: "American Samoa", flag: "🇦🇸", code: "+1-684", isoCode: "AS" },
  { name: "Andorra", flag: "🇦🇩", code: "+376", isoCode: "AD" },
  { name: "Angola", flag: "🇦🇴", code: "+244", isoCode: "AO" },
  { name: "Anguilla", flag: "🇦🇮", code: "+1-264", isoCode: "AI" },
  { name: "Antigua and Barbuda", flag: "🇦🇬", code: "+1-268", isoCode: "AG" },
  { name: "Argentina", flag: "🇦🇷", code: "+54", isoCode: "AR" },
  { name: "Armenia", flag: "🇦🇲", code: "+374", isoCode: "AM" },
  { name: "Aruba", flag: "🇦🇼", code: "+297", isoCode: "AW" },
  { name: "Ascension Island", flag: "🇦🇨", code: "+247", isoCode: "AC" },
  { name: "Australia", flag: "🇦🇺", code: "+61", isoCode: "AU" },
  { name: "Austria", flag: "🇦🇹", code: "+43", isoCode: "AT" },
  { name: "Azerbaijan", flag: "🇦🇿", code: "+994", isoCode: "AZ" },
  { name: "Bahamas", flag: "🇧🇸", code: "+1-242", isoCode: "BS" },
  { name: "Bahrain", flag: "🇧🇭", code: "+973", isoCode: "BH" },
  { name: "Bangladesh", flag: "🇧🇩", code: "+880", isoCode: "BD" },
  { name: "Barbados", flag: "🇧🇧", code: "+1-246", isoCode: "BB" },
  { name: "Belarus", flag: "🇧🇾", code: "+375", isoCode: "BY" },
  { name: "Belgium", flag: "🇧🇪", code: "+32", isoCode: "BE" },
  { name: "Belize", flag: "🇧🇿", code: "+501", isoCode: "BZ" },
  { name: "Benin", flag: "🇧🇯", code: "+229", isoCode: "BJ" },
  { name: "Bermuda", flag: "🇧🇲", code: "+1-441", isoCode: "BM" },
  { name: "Bhutan", flag: "🇧🇹", code: "+975", isoCode: "BT" },
  { name: "Bolivia", flag: "🇧🇴", code: "+591", isoCode: "BO" },
  { name: "Bosnia and Herzegovina", flag: "🇧🇦", code: "+387", isoCode: "BA" },
  { name: "Botswana", flag: "🇧🇼", code: "+267", isoCode: "BW" },
  { name: "Brazil", flag: "🇧🇷", code: "+55", isoCode: "BR" },
  { name: "British Virgin Islands", flag: "🇻🇬", code: "+1-284", isoCode: "VG" },
  { name: "Brunei", flag: "🇧🇳", code: "+673", isoCode: "BN" },
  { name: "Bulgaria", flag: "🇧🇬", code: "+359", isoCode: "BG" },
  { name: "Burkina Faso", flag: "🇧🇫", code: "+226", isoCode: "BF" },
  { name: "Burundi", flag: "🇧🇮", code: "+257", isoCode: "BI" },
  { name: "Cambodia", flag: "🇰🇭", code: "+855", isoCode: "KH" },
  { name: "Cameroon", flag: "🇨🇲", code: "+237", isoCode: "CM" },
  { name: "Canada", flag: "🇨🇦", code: "+1", isoCode: "CA" },
  { name: "Cape Verde", flag: "🇨🇻", code: "+238", isoCode: "CV" },
  { name: "Caribbean Netherlands", flag: "🇧🇶", code: "+599", isoCode: "BQ" },
  { name: "Cayman Islands", flag: "🇰🇾", code: "+1-345", isoCode: "KY" },
  { name: "Central African Republic", flag: "🇨🇫", code: "+236", isoCode: "CF" },
  { name: "Chad", flag: "🇹🇩", code: "+235", isoCode: "TD" },
  { name: "Chile", flag: "🇨🇱", code: "+56", isoCode: "CL" },
  { name: "Christmas Island", flag: "🇨🇽", code: "+61", isoCode: "CX" },
  { name: "Cocos (Keeling) Islands", flag: "🇨🇨", code: "+61", isoCode: "CC" },
  { name: "Colombia", flag: "🇨🇴", code: "+57", isoCode: "CO" },
  { name: "Cook Islands", flag: "🇨🇰", code: "+682", isoCode: "CK" },
  { name: "Costa Rica", flag: "🇨🇷", code: "+506", isoCode: "CR" },
  { name: "Croatia", flag: "🇭🇷", code: "+385", isoCode: "HR" },
  { name: "Curaçao", flag: "🇨🇼", code: "+599", isoCode: "CW" },
  { name: "Cyprus", flag: "🇨🇾", code: "+357", isoCode: "CY" },
  { name: "Czechia", flag: "🇨🇿", code: "+420", isoCode: "CZ" },
  { name: "Denmark", flag: "🇩🇰", code: "+45", isoCode: "DK" },
  { name: "Djibouti", flag: "🇩🇯", code: "+253", isoCode: "DJ" },
  { name: "Dominica", flag: "🇩🇲", code: "+1-767", isoCode: "DM" },
  { name: "Dominican Republic", flag: "🇩🇴", code: "+1-809", isoCode: "DO" },
  { name: "Ecuador", flag: "🇪🇨", code: "+593", isoCode: "EC" },
  { name: "Egypt", flag: "🇪🇬", code: "+20", isoCode: "EG" },
  { name: "El Salvador", flag: "🇸🇻", code: "+503", isoCode: "SV" },
  { name: "Equatorial Guinea", flag: "🇬🇶", code: "+240", isoCode: "GQ" },
  { name: "Eritrea", flag: "🇪🇷", code: "+291", isoCode: "ER" },
  { name: "Estonia", flag: "🇪🇪", code: "+372", isoCode: "EE" },
  { name: "Eswatini", flag: "🇸🇿", code: "+268", isoCode: "SZ" },
  { name: "Ethiopia", flag: "🇪🇹", code: "+251", isoCode: "ET" },
  { name: "Falkland Islands (Malvinas)", flag: "🇫🇰", code: "+500", isoCode: "FK" },
  { name: "Faroe Islands", flag: "🇫🇴", code: "+298", isoCode: "FO" },
  { name: "Fiji", flag: "🇫🇯", code: "+679", isoCode: "FJ" },
  { name: "Finland", flag: "🇫🇮", code: "+358", isoCode: "FI" },
  { name: "France", flag: "🇫🇷", code: "+33", isoCode: "FR" },
  { name: "French Guiana", flag: "🇬🇫", code: "+594", isoCode: "GF" },
  { name: "French Polynesia", flag: "🇵🇫", code: "+689", isoCode: "PF" },
  { name: "Gabon", flag: "🇬🇦", code: "+241", isoCode: "GA" },
  { name: "Gambia", flag: "🇬🇲", code: "+220", isoCode: "GM" },
  { name: "Georgia", flag: "🇬🇪", code: "+995", isoCode: "GE" },
  { name: "Germany", flag: "🇩🇪", code: "+49", isoCode: "DE" },
  { name: "Ghana", flag: "🇬🇭", code: "+233", isoCode: "GH" },
  { name: "Gibraltar", flag: "🇬🇮", code: "+350", isoCode: "GI" },
  { name: "Greece", flag: "🇬🇷", code: "+30", isoCode: "GR" },
  { name: "Greenland", flag: "🇬🇱", code: "+299", isoCode: "GL" },
  { name: "Grenada", flag: "🇬🇩", code: "+1-473", isoCode: "GD" },
  { name: "Guadeloupe", flag: "🇬🇵", code: "+590", isoCode: "GP" },
  { name: "Guam", flag: "🇬🇺", code: "+1-671", isoCode: "GU" },
  { name: "Guatemala", flag: "🇬🇹", code: "+502", isoCode: "GT" },
  { name: "Guernsey", flag: "🇬🇬", code: "+44", isoCode: "GG" },
  { name: "Guinea", flag: "🇬🇳", code: "+224", isoCode: "GN" },
  { name: "Guinea-Bissau", flag: "🇬🇼", code: "+245", isoCode: "GW" },
  { name: "Guyana", flag: "🇬🇾", code: "+592", isoCode: "GY" },
  { name: "Haiti", flag: "🇭🇹", code: "+509", isoCode: "HT" },
  { name: "Honduras", flag: "🇭🇳", code: "+504", isoCode: "HN" },
  { name: "Hong Kong", flag: "🇭🇰", code: "+852", isoCode: "HK" },
  { name: "Hungary", flag: "🇭🇺", code: "+36", isoCode: "HU" },
  { name: "Iceland", flag: "🇮🇸", code: "+354", isoCode: "IS" },
  { name: "Indonesia", flag: "🇮🇩", code: "+62", isoCode: "ID" },
  { name: "Iraq", flag: "🇮🇶", code: "+964", isoCode: "IQ" },
  { name: "Ireland", flag: "🇮🇪", code: "+353", isoCode: "IE" },
  { name: "Isle of Man", flag: "🇮🇲", code: "+44", isoCode: "IM" },
  { name: "Israel", flag: "🇮🇱", code: "+972", isoCode: "IL" },
  { name: "Italy", flag: "🇮🇹", code: "+39", isoCode: "IT" },
  { name: "Jamaica", flag: "🇯🇲", code: "+1-876", isoCode: "JM" },
  { name: "Japan", flag: "🇯🇵", code: "+81", isoCode: "JP" },
  { name: "Jersey", flag: "🇯🇪", code: "+44", isoCode: "JE" },
  { name: "Jordan", flag: "🇯🇴", code: "+962", isoCode: "JO" },
  { name: "Kazakhstan", flag: "🇰🇿", code: "+7", isoCode: "KZ" },
  { name: "Kenya", flag: "🇰🇪", code: "+254", isoCode: "KE" },
  { name: "Kiribati", flag: "🇰🇮", code: "+686", isoCode: "KI" },
  { name: "Kuwait", flag: "🇰🇼", code: "+965", isoCode: "KW" },
  { name: "Kyrgyzstan", flag: "🇰🇬", code: "+996", isoCode: "KG" },
  { name: "Laos", flag: "🇱🇦", code: "+856", isoCode: "LA" },
  { name: "Latvia", flag: "🇱🇻", code: "+371", isoCode: "LV" },
  { name: "Lebanon", flag: "🇱🇧", code: "+961", isoCode: "LB" },
  { name: "Lesotho", flag: "🇱🇸", code: "+266", isoCode: "LS" },
  { name: "Liberia", flag: "🇱🇷", code: "+231", isoCode: "LR" },
  { name: "Libya", flag: "🇱🇾", code: "+218", isoCode: "LY" },
  { name: "Liechtenstein", flag: "🇱🇮", code: "+423", isoCode: "LI" },
  { name: "Lithuania", flag: "🇱🇹", code: "+370", isoCode: "LT" },
  { name: "Luxembourg", flag: "🇱🇺", code: "+352", isoCode: "LU" },
  { name: "Macao", flag: "🇲🇴", code: "+853", isoCode: "MO" },
  { name: "Madagascar", flag: "🇲🇬", code: "+261", isoCode: "MG" },
  { name: "Malawi", flag: "🇲🇼", code: "+265", isoCode: "MW" },
  { name: "Malaysia", flag: "🇲🇾", code: "+60", isoCode: "MY" },
  { name: "Maldives", flag: "🇲🇻", code: "+960", isoCode: "MV" },
  { name: "Mali", flag: "🇲🇱", code: "+223", isoCode: "ML" },
  { name: "Malta", flag: "🇲🇹", code: "+356", isoCode: "MT" },
  { name: "Marshall Islands", flag: "🇲🇭", code: "+692", isoCode: "MH" },
  { name: "Martinique", flag: "🇲🇶", code: "+596", isoCode: "MQ" },
  { name: "Mauritania", flag: "🇲🇷", code: "+222", isoCode: "MR" },
  { name: "Mauritius", flag: "🇲🇺", code: "+230", isoCode: "MU" },
  { name: "Mayotte", flag: "🇾🇹", code: "+262", isoCode: "YT" },
  { name: "Mexico", flag: "🇲🇽", code: "+52", isoCode: "MX" },
  { name: "Micronesia", flag: "🇫🇲", code: "+691", isoCode: "FM" },
  { name: "Moldova", flag: "🇲🇩", code: "+373", isoCode: "MD" },
  { name: "Monaco", flag: "🇲🇨", code: "+377", isoCode: "MC" },
  { name: "Mongolia", flag: "🇲🇳", code: "+976", isoCode: "MN" },
  { name: "Montenegro", flag: "🇲🇪", code: "+382", isoCode: "ME" },
  { name: "Montserrat", flag: "🇲🇸", code: "+1-664", isoCode: "MS" },
  { name: "Morocco", flag: "🇲🇦", code: "+212", isoCode: "MA" },
  { name: "Mozambique", flag: "🇲🇿", code: "+258", isoCode: "MZ" },
  { name: "Myanmar", flag: "🇲🇲", code: "+95", isoCode: "MM" },
  { name: "Namibia", flag: "🇳🇦", code: "+264", isoCode: "NA" },
  { name: "Nauru", flag: "🇳🇷", code: "+674", isoCode: "NR" },
  { name: "Nepal", flag: "🇳🇵", code: "+977", isoCode: "NP" },
  { name: "Netherlands", flag: "🇳🇱", code: "+31", isoCode: "NL" },
  { name: "New Caledonia", flag: "🇳🇨", code: "+687", isoCode: "NC" },
  { name: "New Zealand", flag: "🇳🇿", code: "+64", isoCode: "NZ" },
  { name: "Nicaragua", flag: "🇳🇮", code: "+505", isoCode: "NI" },
  { name: "Niger", flag: "🇳🇪", code: "+227", isoCode: "NE" },
  { name: "Nigeria", flag: "🇳🇬", code: "+234", isoCode: "NG" },
  { name: "Niue", flag: "🇳🇺", code: "+683", isoCode: "NU" },
  { name: "Norfolk Island", flag: "🇳🇫", code: "+672", isoCode: "NF" },
  { name: "Northern Mariana Islands", flag: "🇲🇵", code: "+1-670", isoCode: "MP" },
  { name: "Norway", flag: "🇳🇴", code: "+47", isoCode: "NO" },
  { name: "Oman", flag: "🇴🇲", code: "+968", isoCode: "OM" },
  { name: "Palestine", flag: "🇵🇸", code: "+970", isoCode: "PS" },
  { name: "Panama", flag: "🇵🇦", code: "+507", isoCode: "PA" },
  { name: "Papua New Guinea", flag: "🇵🇬", code: "+675", isoCode: "PG" },
  { name: "Paraguay", flag: "🇵🇾", code: "+595", isoCode: "PY" },
  { name: "Peru", flag: "🇵🇪", code: "+51", isoCode: "PE" },
  { name: "Philippines", flag: "🇵🇭", code: "+63", isoCode: "PH" },
  { name: "Poland", flag: "🇵🇱", code: "+48", isoCode: "PL" },
  { name: "Portugal", flag: "🇵🇹", code: "+351", isoCode: "PT" },
  { name: "Puerto Rico", flag: "🇵🇷", code: "+1-787", isoCode: "PR" },
  { name: "Qatar", flag: "🇶🇦", code: "+974", isoCode: "QA" },
  { name: "Reunion", flag: "🇷🇪", code: "+262", isoCode: "RE" },
  { name: "Romania", flag: "🇷🇴", code: "+40", isoCode: "RO" },
  { name: "Russian Federation", flag: "🇷🇺", code: "+7", isoCode: "RU" },
  { name: "Rwanda", flag: "🇷🇼", code: "+250", isoCode: "RW" },
  { name: "Saint Barthelemy", flag: "🇧🇱", code: "+590", isoCode: "BL" },
  { name: "Saint Kitts and Nevis", flag: "🇰🇳", code: "+1-869", isoCode: "KN" },
  { name: "Saint Lucia", flag: "🇱🇨", code: "+1-758", isoCode: "LC" },
  { name: "Saint Martin", flag: "🇲🇫", code: "+590", isoCode: "MF" },
  { name: "St. Pierre and Miquelon", flag: "🇵🇲", code: "+508", isoCode: "PM" },
  { name: "Saint Vincent and the Grenadines", flag: "🇻🇨", code: "+1-784", isoCode: "VC" },
  { name: "Samoa", flag: "🇼🇸", code: "+685", isoCode: "WS" },
  { name: "San Marino", flag: "🇸🇲", code: "+378", isoCode: "SM" },
  { name: "Sao Tome and Principe", flag: "🇸🇹", code: "+239", isoCode: "ST" },
  { name: "Saudi Arabia", flag: "🇸🇦", code: "+966", isoCode: "SA" },
  { name: "Senegal", flag: "🇸🇳", code: "+221", isoCode: "SN" },
  { name: "Serbia", flag: "🇷🇸", code: "+381", isoCode: "RS" },
  { name: "Seychelles", flag: "🇸🇨", code: "+248", isoCode: "SC" },
  { name: "Sierra Leone", flag: "🇸🇱", code: "+232", isoCode: "SL" },
  { name: "Singapore", flag: "🇸🇬", code: "+65", isoCode: "SG" },
  { name: "Sint Maarten", flag: "🇸🇽", code: "+1-721", isoCode: "SX" },
  { name: "Slovakia (Slovak Republic)", flag: "🇸🇰", code: "+421", isoCode: "SK" },
  { name: "Slovenia", flag: "🇸🇮", code: "+386", isoCode: "SI" },
  { name: "Solomon Islands", flag: "🇸🇧", code: "+677", isoCode: "SB" },
  { name: "Somalia", flag: "🇸🇴", code: "+252", isoCode: "SO" },
  { name: "South Africa", flag: "🇿🇦", code: "+27", isoCode: "ZA" },
  { name: "South Georgia and the Sandwich Islands", flag: "🇬🇸", code: "+500", isoCode: "GS" },
  { name: "South Sudan", flag: "🇸🇸", code: "+211", isoCode: "SS" },
  { name: "Spain", flag: "🇪🇸", code: "+34", isoCode: "ES" },
  { name: "Sri Lanka", flag: "🇱🇰", code: "+94", isoCode: "LK" },
  { name: "Suriname", flag: "🇸🇷", code: "+597", isoCode: "SR" },
  { name: "Swaziland", flag: "🇸🇿", code: "+268", isoCode: "SZ" },
  { name: "Sweden", flag: "🇸🇪", code: "+46", isoCode: "SE" },
  { name: "Switzerland", flag: "🇨🇭", code: "+41", isoCode: "CH" },
  { name: "Taiwan, China", flag: "🇹🇼", code: "+886", isoCode: "TW" },
  { name: "Tajikistan", flag: "🇹🇯", code: "+992", isoCode: "TJ" },
  { name: "Tanzania", flag: "🇹🇿", code: "+255", isoCode: "TZ" },
  { name: "Thailand", flag: "🇹🇭", code: "+66", isoCode: "TH" },
  { name: "Togo", flag: "🇹🇬", code: "+228", isoCode: "TG" },
  { name: "Tonga", flag: "🇹🇴", code: "+676", isoCode: "TO" },
  { name: "Trinidad and Tobago", flag: "🇹🇹", code: "+1-868", isoCode: "TT" },
  { name: "Tunisia", flag: "🇹🇳", code: "+216", isoCode: "TN" },
  { name: "Turkey", flag: "🇹🇷", code: "+90", isoCode: "TR" },
  { name: "Turkmenistan", flag: "🇹🇲", code: "+993", isoCode: "TM" },
  { name: "Turks and Caicos Islands", flag: "🇹🇨", code: "+1-649", isoCode: "TC" },
  { name: "Tuvalu", flag: "🇹🇻", code: "+688", isoCode: "TV" },
  { name: "Uganda", flag: "🇺🇬", code: "+256", isoCode: "UG" },
  { name: "Ukraine", flag: "🇺🇦", code: "+380", isoCode: "UA" },
  { name: "United Arab Emirates", flag: "🇦🇪", code: "+971", isoCode: "AE" },
  { name: "United Kingdom", flag: "🇬🇧", code: "+44", isoCode: "GB" },
  { name: "Uruguay", flag: "🇺🇾", code: "+598", isoCode: "UY" },
  { name: "Uzbekistan", flag: "🇺🇿", code: "+998", isoCode: "UZ" },
  { name: "Vanuatu", flag: "🇻🇺", code: "+678", isoCode: "VU" },
  { name: "Vatican City State (Holy See)", flag: "🇻🇦", code: "+379", isoCode: "VA" },
  { name: "Venezuela", flag: "🇻🇪", code: "+58", isoCode: "VE" },
  { name: "Vietnam", flag: "🇻🇳", code: "+84", isoCode: "VN" },
  { name: "Wallis And Futuna Islands", flag: "🇼🇫", code: "+681", isoCode: "WF" },
  { name: "Yemen", flag: "🇾🇪", code: "+967", isoCode: "YE" },
  { name: "Zambia", flag: "🇿🇲", code: "+260", isoCode: "ZM" },
  { name: "Zanzibar", flag: "🇹🇿", code: "+255", isoCode: "TZ" },
  { name: "Zimbabwe", flag: "🇿🇼", code: "+263", isoCode: "ZW" }
];